//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrcApi.Models
{
    using SqlSugar;
    using System;
    using System.Collections.Generic;

    [SugarTable("CategoryItems")]//当和数据库名称不一样可以设置别名
    public partial class CategoryItems
    {
        [SugarColumn(IsPrimaryKey = true, IsIdentity = true)]//通过特性设置主键和自增列 
        public int CID { get; set; }
        public string C_Category { get; set; }
        public Nullable<int> CI_ID { get; set; }
        public string CI_Name { get; set; }
    }
}
