//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrcApi.Models
{
    using SqlSugar;
    using System;
    using System.Collections.Generic;

    [SugarTable("UserInfo")]//当和数据库名称不一样可以设置别名
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        [SugarColumn(IsPrimaryKey = true, IsIdentity = true)]//通过特性设置主键和自增列 
        public int UserID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserNumber { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserAge { get; set; }
        public Nullable<int> UserSex { get; set; }
        public string UserTel { get; set; }
        public string UserAddress { get; set; }
        public string UserIphone { get; set; }
        public string UserRemarks { get; set; }
        public Nullable<int> UserStatr { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.DateTime> DimissionTime { get; set; }
        public Nullable<decimal> BasePay { get; set; }
        public Nullable<int> isDel { get; set; }
    

    }
}
